# Generated by Django 4.2.7 on 2024-02-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotAmazon', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_emailk',
            new_name='user_email',
        ),
    ]
